### ISSUE TITLE
Issue with "Disable extension on" function

### ISSUE THREAD

**Issue by Rand-31** [domdomegg/hideytthumbnails-extension#10]
When thumbnail display mode is set to "Hidden", the "disable extension on " "search results page" doesn't work. 
It does work if thumbnail display mode is set to anything else though.

**Comment by domdomegg** [comment]
Thanks for the report! I was able to reproduce this. I'll take a look at fixing this soon.

**Comment by Rand-31** [comment]
Just tried and the fix works. Thanks for the fix and the great extension. :)

**Comment by domdomegg** [comment]
Great, thanks @Rand-31 for the kind words and for confirming the fix is working for you :)
