### ISSUE TITLE
Add easy way to toggle the extension on and off

### ISSUE THREAD

**Issue by shadowchild1234** [domdomegg/hideytthumbnails-extension#2]
in most extensions, theres an option to pause whatever its doing and to unpause it. Here, the only way to see thumbnails again is to uninstall the extension, or spend time messing around with site data options in the extensions menu.

**Comment by domdomegg** [comment]
The primary way of doing this would likely be through an extension icon in the Chrome extensions bar.

A user has also suggested making this toggleable via keyboard shortcut.
