### ISSUE TITLE
Blurring does not work on linux

### ISSUE THREAD

**Issue by CodeCubeNeo** [domdomegg/hideytthumbnails-extension#21]
I have fedora 38, running on x.org (x11) and the video thumbnails are not showing. Even the option to see them when hovering is not working. Thanks for the help.

**Comment by domdomegg** [comment]
Thanks for the report. Can you confirm copy and complete this template, which will help us debug this:

```
**Does the 'Hidden' option work? (yes/no)**

**Do thumbnails just appear as normal (as if you don't have the extension installed) when you set the 'Blurred' option? (yes/explain what you see)**

**Which browser are you using?**

**Does the demo here work? https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur (when you switch between 1.5px and 4em the icon should become more blurry)**

```

**Comment by CodeCubeNeo** [comment]
I am sorry. This is a my bad, the blurring works, I had some other extension hide the thumbnails. I am very sorry for spamming.

**Comment by domdomegg** [comment]
No problem, glad it's working for you :)
