### ISSUE TITLE
Not working on Orion Browser

### ISSUE THREAD

**Issue by TheBillyZee** [domdomegg/hideytthumbnails-extension#24]
The extension installs on the Orion Browser and successfully removes the thumbnails on YouTube. However, it does not open or display.
![08-07-2023 at 10 25 44](https://github.com/domdomegg/hideytthumbnails-extension/assets/33535317/245cb792-0c26-4512-bf3c-0415605ac97e)

**Comment by domdomegg** [comment]
Thanks for the report! I'm not super clear what you mean by 'does not open or display'.

The extension doesn't have a UI that opens specifically on YouTube / on the extension itself. It's configured only through the options page. I'm not sure where that is on Orion, but on Chromium based browsers you can get there by right clicking the extension and then clicking 'Options'.

Could you provide more information as to what you were expecting to happen, and also can you see if you can figure out how to open the options page on Orion?

**Comment by domdomegg** [comment]
Closing this for now as lacking info, if still a problem please reopen with more info
