### ISSUE TITLE
It's broken on Mozilla Firefox 116.0 Manjaro Linux

### ISSUE THREAD

**Issue by elbecerrasoto** [domdomegg/hideytthumbnails-extension#25]
It's broken on Mozilla Firefox 116.0

OS: Manjaro Linux x86_64 
Host: Latitude 5430 
Kernel: 6.1.41-1-MANJARO 
Uptime: 1 hour, 30 mins 
Packages: 1618 (pacman), 13 (flatpak) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Plasma 5.27.6 
WM: kwin

**Comment by domdomegg** [comment]
Thanks for the report - can you clarify what is broken / not working about the extension? Do thumbnails just display as usual, or do they do something else? Or is that you can't install it / get into the options / something else?

Additionally for debugging it would be helpful if you can provide any error messages (e.g. in the browser console) when installing the extension and browsing YouTube. It might also be helpful to narrow down what specifically is causing it by testing with other browsers or computers.

Thanks :)

**Comment by elbecerrasoto** [comment]
OMG I'm so embarrassed, the add-on is working fine,
I got confused with this one https://addons.mozilla.org/en-US/firefox/addon/youtube-audio/

**Comment by domdomegg** [comment]
No worries at all, thank you for taking the time to report issues and thereby get more things fixed in the world in general!

I think you can report issues relating to that extension (if you haven't already) at https://github.com/animeshkundu/youtube-audio
