### ISSUE TITLE
Hovering titles shows embedded player and prevents clicking.

### ISSUE THREAD

**Issue by ImVexed** [domdomegg/hideytthumbnails-extension#26]
https://github.com/domdomegg/hideytthumbnails-extension/assets/10090878/ab15eaa7-86c5-450b-9f22-bf6032570c0d

**Comment by ImVexed** [comment]
Nvm, turning `Inline Playback` off under Settings > Playback and performance fixed it

**Comment by domdomegg** [comment]
Thanks for the report, and good to hear that disabling `Inline Playback` was the solution :)

**Comment by ImVexed** [comment]
Going to re-open this as youtube does not persist the `Inline Playback` option. Every time I restart my machine/browser the option goes back to enabled and I can't click titles again.   

I took a look at the CSS, and under a given `ytd-rich-item-renderer > .content > ytd-rich-grid-media > .dismissible > .thumbnail` is responsible for handling the hover. Deleting the `.thumbnail` class div doesn't change anything visually, but does prevent the preview from playing when I hover.
