### ISSUE TITLE
I want to add some more spacing between the texts & remove the video recomendation from mobile version. 

### ISSUE THREAD

**Issue by parth721** [domdomegg/hideytthumbnails-extension#34]
I had done some tweaks to remove the  recomended videos from mobile version (as default), added spacing between the texts, removed New tags from shorts, And remove thumbnails from channel's videos on yt-mobile (previously not present ). <br> Would you like to add these ?

<img src="https://github.com/domdomegg/hideytthumbnails-extension/assets/112557191/3e1780fe-2610-4fb6-aa96-49300a382909"  width="160"  height="300" />

<img src="https://github.com/domdomegg/hideytthumbnails-extension/assets/112557191/648be72b-8e11-4966-a8e6-f9d00e1b93b0"  width="160"  height="300" />

<img src="https://github.com/domdomegg/hideytthumbnails-extension/assets/112557191/c7770128-4d41-4ffe-90ee-b0b5fb8fa9b7"  width="160"  height="160" />

**Comment by domdomegg** [comment]
Thanks for reaching out! I like the tweaks you've made.

Unfortunately, I think this probably goes beyond the scope of the extension for now and is not something I'd like to take on maintenance for so I'm going to close this for now.

(one exception might be 'remove thumbnails from channel's videos on yt-mobile': I'd be happy to accept this as a contribution)
