### ISSUE TITLE
README/ documentation lacking essential resources

### ISSUE THREAD

**Issue by lis6502** [domdomegg/hideytthumbnails-extension#36]
During my prolonged usage of this Firefox addon i haven't found any link to express my gratitude to the author. 
No Patreon, no Paypal, no Ko-Fi or other cryptowallet addressess.

I believe in software being free, but not costless. Therefore i am occasionally seeking towards paying for software that i've found useful and Hide YT Thumbnails is no exception here. Amount of shitty CLICKME NAO unnaturally twisted faces that i haven't encountered has its financial value.

I expect this critical bug to be fixed in upcoming release.

Sincerely

**Comment by domdomegg** [comment]
Haha thank you! Fixed here, which has been added to the funding details and appears on the GitHub project homepage now: https://adamjones.me/sponsor/
