### ISSUE TITLE
For {Hidden (except when hovered)} : shorts on home page were visible

### ISSUE THREAD

**Issue by hebuildapps** [domdomegg/hideytthumbnails-extension#44]
### Issue: `{Hidden (except when hovered)}` shorts on the homepage are visible, whereas it works perfectly for videos.

**Problem:**  
When hovering over the shorts on the homepage, the hidden functionality isn't applied as expected, making the shorts visible. However, this issue does not occur for regular videos.

**Reference:**  
![Sample-for-shorts-not-working](https://github.com/user-attachments/assets/2c7eac85-0364-4dba-8eb8-228f18b5d5d1)

**Proposed Action:**  
I'll attempt to fix this issue and submit a pull request for review.

Thanks for providing this extension—it's a great tool!

**Comment by domdomegg** [comment]
Fixed in https://github.com/domdomegg/hideytthumbnails-extension/commit/74296b1c2d4aec945daa8058306fd7b966f7f9db
